miweb_homepage:
    pattern:  /
    defaults: { _controller: MiwebBundle:Default:index }

categoria:
    resource: "@MiwebBundle/Resources/config/routing_categoria.yml"
    prefix:   /categoria


productos:
    resource: "@MiwebBundle/Resources/config/routing_producto.yml"
    prefix:   /producto