miweb_homepage:
    pattern:  /
    defaults: { _controller: MiwebBundle:Default:index }

_categoria:
    resource: "@MiwebBundle/Resources/config/routing_categoria.yml"
    prefix:   /categoria


_productos:
    resource: "@MiwebBundle/Resources/config/routing_producto.yml"
    prefix:   /producto

_login:
    resource: "@MiwebBundle/Resources/config/login.yml"
    prefix:   /