jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Miweb\MiwebBundle\Entity\Core\Usuario: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administradores:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        usuarios:
            entity: { class: Miweb\MiwebBundle\Entity\Usuario, property: correo  }
    firewalls:
        categoria_nuevo:
            pattern:    ^/categoria/nuevo
            http_basic: 
                realm: "Secured Demo Area"

        categoria_editar:
            pattern:    ^/categoria/editar
            provider:  administradores
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:   logout
                target: categoria_listar

        publico:
            pattern:    ^/
            #pattern:    ^/demo/secured/
            #form_login:
            #    check_path: _security_check
            #    login_path: _demo_login
            #logout:
            #    path:   _demo_logout
            #    target: _demo


            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/categoria/nuevo, roles: ROLE_ADMIN }
        - { path: ^/categoria/editar, roles: ROLE_ADMIN }
