producto:
    pattern:  /
    defaults: { _controller: "PruebaBundle:Producto:index" }

producto_show:
    pattern:  /{id}/show
    defaults: { _controller: "PruebaBundle:Producto:show" }

producto_new:
    pattern:  /new
    defaults: { _controller: "PruebaBundle:Producto:new" }

producto_create:
    pattern:  /create
    defaults: { _controller: "PruebaBundle:Producto:create" }
    requirements: { _method: post }

producto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PruebaBundle:Producto:edit" }

producto_update:
    pattern:  /{id}/update
    defaults: { _controller: "PruebaBundle:Producto:update" }
    requirements: { _method: post|put }

producto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PruebaBundle:Producto:delete" }
    requirements: { _method: post|delete }
